---
- name: Setup doorbell
  hosts: all
  connection: local

  vars_files:

    - vars/vault.yml
  
  tasks:

    - name: make directory /var/lib/doorbell
      file:
        path: /var/lib/doorbell
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: template scripts
      template:
        src: "{{ item }}.j2"
        dest: "/var/lib/doorbell/{{ item }}"
        owner: root
        group: root
        mode: '0755'
      with_items:
        - button_handler
        - ring_chime

    - name: template service files
      template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - button_handler.service
        - ring_chime.service

    - name: send message to slack
      slack:
        token: "{{ slack_token }}"
        msg: "{{ inventory_hostname }} running ansible"
        username: queenbot
        icon_url: 'https://i.imgur.com/o8UhqtS.jpg'


