---
- name: Setup doorbell
  hosts: all
  connection: local

  vars_files:

    - vars/vault.yml
  
  handlers:

    - name: reload systemd
      shell: /bin/systemctl daemon-reload

  tasks:

    - name: make directory /var/lib/doorbell
      file:
        path: /var/lib/doorbell
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: template scripts
      template:
        src: "templates/{{ item }}.j2"
        dest: "/var/lib/doorbell/{{ item }}"
        owner: root
        group: root
        mode: '0755'
      with_items:
        - button_handler
        - ring_chime

    - name: template service files
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - button_handler.service
        - ring_chime.service
      notify:
        - reload systemd

    - name: start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - button_handler
        - ring_chime

    - name: setup cron job
      #/usr/local/bin/ansible-pull -d /var/lib/ansible/doorbell --url https://github.com/goozbach/doorbell-scripts.git -i inv/
      cron:
        name: ansible-pull
        weekday: "*"
        minute: 13
        hour: "*"
        user: root
        job: "/usr/local/bin/ansible-pull -d /var/lib/ansible/doorbell --url https://github.com/goozbach/doorbell-scripts.git -i inv/"
        cron_file: ansible-pull

    - name: send message to slack
      slack:
        token: "{{ slack_token }}"
        msg: "{{ inventory_hostname }} running ansible"
        username: queenbot
        icon_url: 'https://i.imgur.com/o8UhqtS.jpg'

